[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cult-common = { path = "../cult-common/" }
actix-web = "4.5.1"
tokio = "1.37.0"
tokio-tungstenite = "0.21.0"
