name: Rust Build

on:
  push:
    branches: [ "main","app-websocket" ]
  pull_request:
    branches: [ "main","app-websocket" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2.7.3
        with:
          workspaces: "server"
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Backend
        run: |
          cd server
          cargo build --verbose
